global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - node-exporter.local:9100 # Scrape Node-Exporter
       - prometheus.local:9090 # Scrape Prometheus